# Generated by Django 4.0 on 2021-12-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
