# Generated by Django 4.0 on 2021-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='todo',
        ),
        migrations.AddField(
            model_name='todos',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
    ]
