# Generated by Django 4.0 on 2021-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_todos_todo_todos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='todos',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
