# Generated by Django 4.0 on 2021-12-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_person_alter_todos_description_alter_todos_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
    ]
