# Generated by Django 4.0.2 on 2022-02-17 21:32

import django.core.validators
from django.db import migrations, models
import expenses_tracker.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[expenses_tracker.profiles.models.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=15, validators=[expenses_tracker.profiles.models.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_image', models.FileField(upload_to='profiles', validators=[expenses_tracker.profiles.models.MaxFileSizeValueValidator(5)])),
            ],
        ),
    ]
