# Generated by Django 4.0.4 on 2022-04-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='text',
        ),
    ]
