# Generated by Django 4.0 on 2021-12-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
