# Generated by Django 4.0.2 on 2022-02-21 14:58

from django.db import migrations, models
import petstagram.pets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_user_profile_alter_pet_unique_together_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[petstagram.pets.validators.MaxSizeFileInMbValidator]),
        ),
    ]
