# Generated by Django 4.0.2 on 2022-02-22 15:41

from django.db import migrations, models
import petstagram.pets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos', validators=[petstagram.pets.validators.MaxSizeFileInMbValidator]),
        ),
    ]
